# .github/workflows/format.yml
name: Auto Format Java Code and Create PR

on:
  push:
    branches: [ "main" ]

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check if actor is a bot (prevent infinite loop)
        if: github.actor == 'github-actions[bot]'
        run: |
          echo "Skip formatting triggered by bot"
          exit 0

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Check code formatting with Spotless
        run: mvn spotless:check || true  # Continue even if check fails

      - name: Run Spotless to auto-format code
        run: mvn spotless:apply

      - name: Check for changes
        id: changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Set branch name
        if: steps.changes.outputs.changes == 'true'
        id: vars
        run: echo "branch=auto/format-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create branch, commit, and push
        if: steps.changes.outputs.changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b ${{ steps.vars.outputs.branch }}
          git add .
          git commit -m "chore(format): auto-format code with Spotless"
          git push origin ${{ steps.vars.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        if: steps.changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore(format): auto-format code with Spotless"
          body: "This PR contains automatic code formatting changes."
          branch: ${{ steps.vars.outputs.branch }}
          base: main
          delete-branch: true