# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Check code formatting with Spotless
      run: mvn spotless:check

    - name: Build with Maven
      run: mvn -B package --file pom.xml


    - name: Create .env file
      run: |
        cat <<EOF > .env
        MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
        ZOOKEEPER_CLIENT_PORT=${{ secrets.ZOOKEEPER_CLIENT_PORT }}
        SPRING_MAIL_USERNAME=${{ secrets.SPRING_MAIL_USERNAME }}
        SPRING_MAIL_PASSWORD=${{ secrets.SPRING_MAIL_PASSWORD }}
        SPRING_MAIL_HOST=${{ secrets.SPRING_MAIL_HOST }}
        SPRING_MAIL_PORT=${{ secrets.SPRING_MAIL_PORT }}
        CLUSTER_ID=${{ secrets.CLUSTER_ID }}
        EOF

    - name: Build Docker image
      run: docker build -t app:latest .

    - name: Run docker-compose
      run: docker-compose up -d

    - name: Show running containers
      run: docker ps -a

    - name: Tear down docker-compose
      if: always()
      run: docker-compose down